applications/urls.py
from django.urls import path

from applications.views import send_applic, whating_applic, all_applic, change_status

app_name = 'applications'

urlpatterns = [
    path('send_applic/', send_applic, name='send_applic'),
    path('whate_applic/', whating_applic, name='whate_applic'),
    path('all_applic/', all_applic, name='all_applic'),
    path('change_status/<int:applic_id>/', change_status, name='change_status'),
]

auth/urls.py
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy
from django.views.generic import CreateView

from auth.forms import CustomAuthenticationForm, CustomUserCreationForm

app_name = 'custom_auth'

urlpatterns = [
    path('sign-in/', LoginView.as_view(template_name='auth/sign-in.html', next_page=reverse_lazy('main:home'),
                                       form_class=CustomAuthenticationForm, extra_context={'sign_in_active': 'active'}),
         name='sign-in'),
    path('sign-up/', CreateView.as_view(template_name='auth/sign-up.html', success_url=reverse_lazy('auth:sign-in'),
                                        form_class=CustomUserCreationForm, extra_context={'sign_up_active': 'active'},
                                        model=User), name='sign-up'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('auth:sign-in')), name='logout'),
]

creditor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('auth/', include('auth.urls', namespace='auth')),
    path('applic/', include('applications.urls', namespace='applic')),
]

main/urls.py
from django.urls import path

from main.views import home, contact

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('about_us/', contact, name='contact'),
]

applications/models.py
from django.contrib.auth.models import User
from django.db import models


class Credit(models.Model):
    class Purpose(models.TextChoices):
        just = 'just', 'Просто деньги'
        refinancing = 'refinancing', 'Рефинансирование кредита'
        car = 'car', 'Новая машина'
        realestate = 'realestate', 'Недвижимость'
        mortgage = 'mortgage', 'Ипотека'

    class Status(models.TextChoices):
        new = 'new', 'Новая'
        no = 'no', 'Неодобренна'
        yes = 'yes', 'Одобренна'

    price = models.DecimalField(max_digits=100, decimal_places=2, verbose_name='Сумма')
    purpose = models.CharField(choices=Purpose.choices, default=Purpose.just, max_length=15, verbose_name='Цель кредита')
    city = models.CharField(max_length=20, verbose_name='Город')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    status = models.CharField(max_length=15, choices=Status.choices, default=Status.new, verbose_name='Статус')

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'

main/models.py
from django.db import models

# Create your models here.

applications/forms.py
from django import forms

from applications.models import Credit


class CreditForm(forms.ModelForm):
    class Meta:
        model = Credit
        fields = ['price', 'purpose', 'city']

    def save(self, user, commit=True):
        credit = super().save(commit=False)
        credit.user = user
        return super(CreditForm, self).save()


class ChangeStatusForm(forms.ModelForm):
    class Meta:
        model = Credit
        fields = ['status']

        widgets = {
            'status': forms.Select(choices=Credit.Status.choices)
        }

applications/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from applications.forms import CreditForm

from applications.models import Credit


@login_required(login_url='auth:sign-in')
def send_applic(request):
    if request.method == 'POST':
        form = CreditForm(request.POST)
        if form.is_valid():
            form.save(request.user)
            return redirect('applic:send_applic')
    form = CreditForm()
    return render(request, 'applications/send_applic.html', {'form': form})


@login_required(login_url='auth:sign-in')
def whating_applic(request):
    applic = Credit.objects.filter(user=request.user)
    return render(request, 'applications/whating_applic.html', {'applic': applic})


@staff_member_required()
def all_applic(request):
    applic = Credit.objects.all
    return render(request, 'applications/all_applic.html', {'applic': applic})


@staff_member_required()
def change_status(request, applic_id):
    applic = get_object_or_404(Credit, id=applic_id)

    if request.method == 'POST':

        new_status = request.POST.get('status')
        applic.status = new_status
        applic.save()

    return render(request, 'applications/change_status.html', {'applic': applic})

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')


def contact(request):
    return render(request, 'main/about_us.html')

applications/templates/applications/all_applic.html
{% extends 'layout.html' %}

{% block title %} <title>Заявки пользователей</title> {% endblock %}

{% block content %}
    <div class="content">
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Пользователь</th>
                <th scope="col">Сумма</th>
                <th scope="col">Цель кредита</th>
                <th scope="col">Статус</th>
            </tr>
            </thead>
            <tbody>
            {% for item in applic %}
                <tr>
                    <th scope="row">{{ item.id }}</th>
                    <td>{{ item.user }}</td>
                    <td>{{ item.price }}</td>
                    <td>{{ item.purpose }}</td>
                    <td>
                        {{ item.get_status_display }}
                    </td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'applic:change_status' item.id %}">Изменить статус заявки</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

applications/templates/applications/change_status.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}<title>Изменение статуса заявки</title>{% endblock %}

{% block content %}
        <form method="post" action="{% url 'applic:change_status' applic.id %}">
            {% csrf_token %}
            <label for="status">Изменить статус:</label>
            <label>
                <select class="form-select" name="status">
                    {% for status, _ in applic.Status.choices %}
                        <option value="{{ status }}" {% if applic.status == status %}selected{% endif %}>{{ status }}</option>
                    {% endfor %}
                </select>
            </label>
            <button class="btn btn-primary" type="submit">Изменить</button>
        </form>
{% endblock %}

applications/templates/applications/send_applic.html
{% extends 'layout.html' %}

{% block title %} <title>Взять кредит</title> {% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Отправить">
    </form>
{% endblock %}

applications/templates/applications/whating_applic.html
{% extends 'layout.html' %}

{% block title %} <title>Ваши заявки</title> {% endblock %}

{% block content %}
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Сумма</th>
            <th scope="col">Цель кредита</th>
            <th scope="col">Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for item in applic %}
            <tr>
                <th scope="row">{{ item.id }}</th>
                <td>{{ item.price }}</td>
                <td>{{ item.purpose }}</td>
                <td>
                    {{ item.get_status_display }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

main/templates/main/about_us.html
{% extends 'layout.html' %}

{% load static %}

{% block title %} <title>О нас</title> {% endblock %}

{% block content %}
    <div class="content">
        <div class="contact_info">
            <h1 style="color: white">Контакты</h1>
            <p style="width: 800px; color: white">В случае чего — мы обязательно поможем. По телефону, электронной
                почте, в соцсетях и мессенджерах. Ниже вы
                легко найдёте контакт, связанный с вашим вопросом.</p>
            <div class="telefon">
                <div class="telefon_info">
                    <div>
                        <h1 style="color: white">Служба заботы о клиентах</h1>
                        <p style="color: white; width: 600px; margin-right: 20px">Ответим на любой вопрос, связанный с
                            работой сайта, и проконсультируем по услугам и предложениям. Звоните или пишите на
                            creditor@mail.ru</p>
                    </div>
                    <img src="{% static 'img/contact-telefon.png' %}" alt="">
                </div>
            </div>

            <hr style="background: white">

            <div class="rekvisit">
                <div>
                    <h1 style="color: white">Реквизиты и адрес</h1>
                    <p style="color: white">ООО «Кредитор» <br>
                        ОГРН 1087756642774 <br>
                        Юридический и фактический адрес: <br>
                        108544, г. Курган, солнечный бульвар, <br>
                        дом 6, 5 этаж <br>
                        График работы: <br>
                        с понедельника по субботу <br>
                        с 8 до 22 часов по курганскому времени</p>
                </div>
                <iframe style="border-radius: 20px" src="https://yandex.ru/map-widget/v1/?um=constructor%3Aacebf78fb36bf9faf80e3de13f15d91907174cda2a8f2f3c5c17926559ffb8d4&amp;source=constructor"
                        width="600" height="400" frameborder="0"></iframe>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/home.html
{% extends 'layout.html' %}

{% block title %}<title>Главная</title>{% endblock %}

{% block content %}
    <div class="content">
        <h1>Помогаем в трудный момент жизни!</h1>
        <div class="blocks">
            <div class="block-info">
                <p style="font-weight: 700; margin-bottom: 0">Займы</p>
                <p style="opacity: 60%">На карту за 10 минут</p>
                <div class="footer_block">
                    <p style="background: #4c0bce; font-size: 15px; border-radius: 10px; padding: 0 3px 0 3px; width: max-content; color: white; margin-bottom: 0">
                        от 0%</p>
                    <i class="bi bi-credit-card"></i>
                </div>
            </div>

            <div class="block-info">
                <p style="font-weight: 700; margin-bottom: 0">Страхование ипотеки</p>
                <p style="opacity: 60%">Страховка для банка</p>
                <div class="footer_block">
                    <p style="background: #4c0bce; font-size: 15px; border-radius: 10px; padding: 0 3px 0 3px; width: max-content; color: white; margin-bottom: 0">
                        приз 500 000 руб.</p>
                    <i class="bi bi-bank"></i>
                </div>
            </div>

            <div class="block-info">
                <p style="font-weight: 700; margin-bottom: 0">Вклады</p>
                <p style="opacity: 60%">Найдите лучшую ставку</p>
                <div style="justify-content: flex-end" class="footer_block">
                    <i class="bi bi-safe"></i>
                </div>
            </div>

            <div class="block-info">
                <p style="font-weight: 700; margin-bottom: 0">Ипотека</p>
                <p style="opacity: 60%">Одна заявка в 9 банков</p>
                <div style="justify-content: flex-end" class="footer_block">
                    <i class="bi bi-house"></i>
                </div>
            </div>

            <div style="display: flex; flex-direction: column; justify-content: space-between" class="block-info">
                <p style="font-weight: 700; margin-bottom: 0">Туристическая страховка</p>
                <div style="justify-content: flex-end" class="footer_block">
                    <i class="bi bi-airplane"></i>
                </div>
            </div>

            <div style="display: flex; flex-direction: column; justify-content: space-between" class="block-info">
                <p style="font-weight: 700; margin-bottom: 0">Страхование спортсменов</p>
                <div style="justify-content: flex-end" class="footer_block">
                    <i class="bi bi-trophy"></i>
                </div>
            </div>
        </div>
        <a type="button" href="{% url 'applic:send_applic' %}" class="btn btn-outline-primary">Взять кредит</a>
    </div>
{% endblock %}

templates/layout.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block title %}<title></title>{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'main:home' %}">Кредитор</a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav me-auto mb-3 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:contact' %}">О нас</a>
                </li>
                {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'applic:all_applic' %}">Просмотр всех заявок</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'applic:send_applic' %}">Взять кредит</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'applic:whate_applic' %}">Мои заявки на кредит</a>
                    </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <p class="navbar">Вошли как {{ user.username }}</p>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:logout' %}">Выйти</a>
                    </li>
                </ul>
            {% else %}
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:sign-in' %}">Авторизация</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:sign-up' %}">Регистрация</a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>
{% block content %}

{% endblock %}
<footer class="text-center bg-body-tertiary fixed-bottom" style="background-color: rgba(0, 0, 0, 0.05);">
    <!-- Grid container -->
    <div class="container pt-4">
        <!-- Section: Social media -->
        <section class="mb-4">

            <!-- Google -->
            <a
                    data-mdb-ripple-init
                    class="btn btn-link btn-floating btn-lg text-body m-1"
                    href="#!"
                    role="button"
                    data-mdb-ripple-color="dark"
            ><i class="bi bi-google"></i></a>

            <a
                    data-mdb-ripple-init
                    class="btn btn-link btn-floating btn-lg text-body m-1"
                    href="#!"
                    role="button"
                    data-mdb-ripple-color="dark"
            ><i class="bi bi-telegram"></i></a>

            <a
                    data-mdb-ripple-init
                    class="btn btn-link btn-floating btn-lg text-body m-1"
                    href="#!"
                    role="button"
                    data-mdb-ripple-color="dark"
            ><i class="bi bi-whatsapp"></i></a>
        </section>
        <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2024 Copyright:
        <a class="text-body" href="{% url 'main:home' %}">Creditor</a>
    </div>
    <!-- Copyright -->
</footer>
</body>
</html>